### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by hmomin** [lblaoke/CARDS#1]
Hi, I was wondering if there’s any documentation available to help run the code.

It seems like there are several files, and clear instructions would really enhance the usability of your work for the research community. Good documentation could also increase the impact of your work and potentially lead to more citations.

**Comment by lblaoke** [comment]
We are finalizing the code due to the rebuttal work. The code and README will be updated in a few days.

Thanks for your interest to our work and your patience!

**Comment by lblaoke** [comment]
Thanks for your patience! We've finished all rebuttal works and now the README is complete. You may refer to the instructions to try CARDS on your own machines.
